baseURL = '/'
languageCode = 'en-us'
title = 'SWEN 640'

relativeURLs = true
cleanDestinationDir = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]

[markup.goldmark.renderer]
unsafe = true

[params]
Logo ='se-logo.png'
LogoLink = 'https://www.rit.edu/computing/department-software-engineering'