baseURL = 'https://example.org/'
relativeURLs = true
languageCode = 'en-us'
title = 'SWEN-732'

cleanDestinationDir = true

publishDir = "/home/fall2020/kdd9198/public_html/test-deploy/SWEN-732"
cacheDir = "/home/fall2020/kdd9198/hugo-cache"

[markup.goldmark.renderer]
  unsafe = true