baseURL = 'https://example.org/'
relativeURLs = true
languageCode = 'en-us'
title = 'SWEN-732'

cleanDestinationDir = true
minifyOutput = true
buildDrafts = true

[markup.goldmark.renderer]
  unsafe = true